### PR TITLE
v-img directive can be used with any element

### PR DESCRIPTION
**Pull request by heyitskippy**
Changed in e03bbcd

### CODE REVIEW

**Comment by heyitskippy** [comment]
@fahrenq Привет +)
Don't know how to select only e03bbcd for pull request

**Comment by dev-blinov** [comment]
Anybody resolve conflicts? :)

**Comment by fahrenq** [comment]
@dev-blinov Will do in few days! :) Thanks!

**Comment by iMacTia** [comment]
@fahrenq +1 would be great to have 😄!

**Pull request closed without merging**
