### PR TITLE
add zoom functionality from https://github.com/tolpit/vue-pinch-image

### PR DESCRIPTION
**Pull request by SSShooter**

### CODE REVIEW

**Comment by fahrenq** [comment]
Hey!
Thank you very much for the contribution!
I'll review and merge a bit later today.
Thanks!

**Comment by ssshooter** [comment]
Thank you for your hard work.

**Comment by FrankFlitton** [comment]
Any progress on this? It looks like a great feature to add.

**Comment by SSShooter** [comment]
@FrankFlitton [Here](https://github.com/ssshooter/img-vuer) is a alternative.

**Comment by FrankFlitton** [comment]
@ssshooter Thanks for the suggestion. It works great on mobile but lacks desktop support. I may throw in a PR for mouse event support.

**Pull request closed without merging**
