### PR TITLE
When you add an image to the gallery and then select this image, the …

### PR DESCRIPTION
**Pull request by Gimanh**
When you add an image to the gallery and then select this image, the old image is displayed in the preview.

### CODE REVIEW

**Comment by fahrenq** [comment]
Hey!
Thank you very much for creating PR and make open source great!
However, I can't understand the problem you want to solve with this changes, can you please describe it with some more details?

**Comment by Gimanh** [comment]
HI!
I have gallery in user page

and there is button for add new image 
when user add new image

 and then click them he will see old first image in gallery

in html code we see


with e.src  i dont have this problem

**Comment by fahrenq** [comment]
Well, thank you very much for detailed bug report. Unfortunately switching to the `e.src` will break other piece of functionality.
I'll try to find out how to fix this in other way.
For now you can use plugin from your fork.
Thank you very much!

**Comment by Gimanh** [comment]
Ok, let me know when this bug will fixed. Thanks for v-img!)

**Comment by fahrenq** [comment]
Bug fixed in 0.1.2.

https://github.com/crowdbotics/v-img/commit/dc662bb31bc5aa4b66b6a6e7cd8bb7e440f67499#diff-6d186b954a58d5bb740f73d84fe39073

**Pull request closed without merging**
